# train data analysis

# data collection and data exploration

In [254]:
import  numpy as np
import pandas as pd

In [255]:
df1=pd.read_csv("C:/Users/harin/Downloads/train.csv")
df1.head()

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False   
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False   
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True   
3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False   
4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1        109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2         43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3          0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4        303.0       70.0         151.0   565.0     2.0  Willy Santantines   

   Transported  
0        False  
1         True  
2        False  
3        False  
4         True

In [256]:
df1.shape

(8693, 14)

In [257]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   PassengerId   8693 non-null   object 
 1   HomePlanet    8492 non-null   object 
 2   CryoSleep     8476 non-null   object 
 3   Cabin         8494 non-null   object 
 4   Destination   8511 non-null   object 
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object 
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object 
 13  Transported   8693 non-null   bool   
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB


In [258]:
df1["HomePlanet"].unique()

array(['Europa', 'Earth', 'Mars', nan], dtype=object)

In [259]:
df1["Destination"].unique()

array(['TRAPPIST-1e', 'PSO J318.5-22', '55 Cancri e', nan], dtype=object)

In [260]:
df1["CryoSleep"].unique()

array([False, True, nan], dtype=object)

# data cleaning

#remove duplicates

In [261]:
df1.duplicated().sum()

0

#remove the unwanted columns

In [262]:
df1.drop(columns=["Name","RoomService","Spa","VRDeck","ShoppingMall","FoodCourt","VIP","Cabin","Destination"],axis=1,inplace=True)

In [263]:
df1.head()

PassengerId HomePlanet CryoSleep   Age  Transported
0     0001_01     Europa     False  39.0        False
1     0002_01      Earth     False  24.0         True
2     0003_01     Europa     False  58.0        False
3     0003_02     Europa     False  33.0        False
4     0004_01      Earth     False  16.0         True

#is null value

In [264]:
df1.isnull().sum()

PassengerId      0
HomePlanet     201
CryoSleep      217
Age            179
Transported      0
dtype: int64

In [265]:
df1["Age"].mean()

28.82793046746535

In [266]:
df1["Age"].median()

27.0

In [267]:
df1["Age"].fillna(df1["Age"].mean(),inplace=True)

In [268]:
df1.isnull().sum()

PassengerId      0
HomePlanet     201
CryoSleep      217
Age              0
Transported      0
dtype: int64

In [269]:
homeplanet={
    "Europa":1,
    "Earth":2,
    "Mars":3
}
df1["HomePlanet"].replace(homeplanet,inplace=True)

In [270]:
df1.head()

PassengerId  HomePlanet CryoSleep   Age  Transported
0     0001_01         1.0     False  39.0        False
1     0002_01         2.0     False  24.0         True
2     0003_01         1.0     False  58.0        False
3     0003_02         1.0     False  33.0        False
4     0004_01         2.0     False  16.0         True

In [271]:
df1.isnull().sum()

PassengerId      0
HomePlanet     201
CryoSleep      217
Age              0
Transported      0
dtype: int64

In [272]:
df1["HomePlanet"].median()


2.0

In [273]:
df1["HomePlanet"].fillna(df1["HomePlanet"].median(),inplace=True)

In [274]:
df1.isnull().sum()

PassengerId      0
HomePlanet       0
CryoSleep      217
Age              0
Transported      0
dtype: int64

In [275]:

df1["CryoSleep"].replace(False,0,inplace=True)
df1["CryoSleep"].replace(True,1,inplace=True)

In [276]:
df1.head()

PassengerId  HomePlanet  CryoSleep   Age  Transported
0     0001_01         1.0        0.0  39.0        False
1     0002_01         2.0        0.0  24.0         True
2     0003_01         1.0        0.0  58.0        False
3     0003_02         1.0        0.0  33.0        False
4     0004_01         2.0        0.0  16.0         True

In [277]:
df1["CryoSleep"].mean()

0.35830580462482303

In [278]:
df1["CryoSleep"].fillna(df1["CryoSleep"].median(),inplace=True)

In [279]:
df1.isnull().sum()

PassengerId    0
HomePlanet     0
CryoSleep      0
Age            0
Transported    0
dtype: int64

In [280]:
df1["Transported"].replace(False,0,inplace=True)
df1["Transported"].replace(True,1,inplace=True)

In [281]:
df1.head()

PassengerId  HomePlanet  CryoSleep   Age  Transported
0     0001_01         1.0        0.0  39.0            0
1     0002_01         2.0        0.0  24.0            1
2     0003_01         1.0        0.0  58.0            0
3     0003_02         1.0        0.0  33.0            0
4     0004_01         2.0        0.0  16.0            1

#outlier

In [282]:
df1.skew()

PassengerId    0.002020
HomePlanet     0.048740
CryoSleep      0.632024
Age            0.423478
Transported   -0.014497
dtype: float64

# correlation

In [283]:
corr=df1.corr()

In [284]:
corr

HomePlanet  CryoSleep       Age  Transported
HomePlanet     1.000000  -0.040494 -0.130438    -0.102240
CryoSleep     -0.040494   1.000000 -0.070736     0.460132
Age           -0.130438  -0.070736  1.000000    -0.074249
Transported   -0.102240   0.460132 -0.074249     1.000000

In [285]:
x_train=df1.drop("Transported",axis=1)

In [286]:
x_train

PassengerId  HomePlanet  CryoSleep   Age
0        0001_01         1.0        0.0  39.0
1        0002_01         2.0        0.0  24.0
2        0003_01         1.0        0.0  58.0
3        0003_02         1.0        0.0  33.0
4        0004_01         2.0        0.0  16.0
...          ...         ...        ...   ...
8688     9276_01         1.0        0.0  41.0
8689     9278_01         2.0        1.0  18.0
8690     9279_01         2.0        0.0  26.0
8691     9280_01         1.0        0.0  32.0
8692     9280_02         1.0        0.0  44.0

[8693 rows x 4 columns]

In [287]:
y_train=df1.Transported

In [288]:
y_train

0       0
1       1
2       0
3       0
4       1
       ..
8688    0
8689    0
8690    1
8691    0
8692    1
Name: Transported, Length: 8693, dtype: int64

In [289]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()


In [290]:
model.fit(x_train,y_train)

GaussianNB()

# test data analysis


# data collection and data exploration

In [291]:
import  numpy as np
import pandas as pd

In [292]:
df2=pd.read_csv("C:/Users/harin/Downloads/test.csv")
df2.head()

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0013_01      Earth      True  G/3/S  TRAPPIST-1e  27.0  False   
1     0018_01      Earth     False  F/4/S  TRAPPIST-1e  19.0  False   
2     0019_01     Europa      True  C/0/S  55 Cancri e  31.0  False   
3     0021_01     Europa     False  C/1/S  TRAPPIST-1e  38.0  False   
4     0023_01      Earth     False  F/5/S  TRAPPIST-1e  20.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck              Name  
0          0.0        0.0           0.0     0.0     0.0   Nelly Carsoning  
1          0.0        9.0           0.0  2823.0     0.0    Lerome Peckers  
2          0.0        0.0           0.0     0.0     0.0   Sabih Unhearfus  
3          0.0     6652.0           0.0   181.0   585.0  Meratz Caltilter  
4         10.0        0.0         635.0     0.0     0.0   Brence Harperez

In [293]:
df2.shape

(4277, 13)

In [294]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   PassengerId   4277 non-null   object 
 1   HomePlanet    4190 non-null   object 
 2   CryoSleep     4184 non-null   object 
 3   Cabin         4177 non-null   object 
 4   Destination   4185 non-null   object 
 5   Age           4186 non-null   float64
 6   VIP           4184 non-null   object 
 7   RoomService   4195 non-null   float64
 8   FoodCourt     4171 non-null   float64
 9   ShoppingMall  4179 non-null   float64
 10  Spa           4176 non-null   float64
 11  VRDeck        4197 non-null   float64
 12  Name          4183 non-null   object 
dtypes: float64(6), object(7)
memory usage: 434.5+ KB


# data cleaning

#remove duplicates

In [295]:
df2.duplicated().sum()

0

#remove the unwasted rows

In [296]:
df2.drop(columns=["Name","RoomService","Spa","VRDeck","ShoppingMall","FoodCourt","VIP","Cabin","Destination"],axis=1,inplace=True)

In [297]:
df2.head()

PassengerId HomePlanet CryoSleep   Age
0     0013_01      Earth      True  27.0
1     0018_01      Earth     False  19.0
2     0019_01     Europa      True  31.0
3     0021_01     Europa     False  38.0
4     0023_01      Earth     False  20.0

#isnull

In [298]:
df2.isnull().sum()

PassengerId     0
HomePlanet     87
CryoSleep      93
Age            91
dtype: int64

In [299]:
df2["Age"].mean()

28.65814620162446

In [300]:
df2["Age"].median()

26.0

In [301]:
df2["Age"].fillna(df1["Age"].median(),inplace=True)

In [302]:
df2.isnull().sum()

PassengerId     0
HomePlanet     87
CryoSleep      93
Age             0
dtype: int64

In [303]:
homeplanet={
    "Europa":1,
    "Earth":2,
    "Mars":3
}
df2["HomePlanet"].replace(homeplanet,inplace=True)

In [304]:
df2.head()

PassengerId  HomePlanet CryoSleep   Age
0     0013_01         2.0      True  27.0
1     0018_01         2.0     False  19.0
2     0019_01         1.0      True  31.0
3     0021_01         1.0     False  38.0
4     0023_01         2.0     False  20.0

In [305]:
df2.isnull().sum()

PassengerId     0
HomePlanet     87
CryoSleep      93
Age             0
dtype: int64

In [306]:
df2["HomePlanet"].median()

2.0

In [307]:
df2["HomePlanet"].fillna(df2["HomePlanet"].median(),inplace=True)

In [308]:
df2.isnull().sum()

PassengerId     0
HomePlanet      0
CryoSleep      93
Age             0
dtype: int64

In [309]:
df2["CryoSleep"].replace(False,0,inplace=True)
df2["CryoSleep"].replace(True,1,inplace=True)

In [310]:
df2.head()

PassengerId  HomePlanet  CryoSleep   Age
0     0013_01         2.0        1.0  27.0
1     0018_01         2.0        0.0  19.0
2     0019_01         1.0        1.0  31.0
3     0021_01         1.0        0.0  38.0
4     0023_01         2.0        0.0  20.0

In [311]:
df2["CryoSleep"].mean()

0.3690248565965583

In [312]:
df2["CryoSleep"].fillna(df2["CryoSleep"].median(),inplace=True)

In [313]:
df2.isnull().sum()

PassengerId    0
HomePlanet     0
CryoSleep      0
Age            0
dtype: int64

#outlier

In [314]:
df2.skew()

PassengerId    0.001058
HomePlanet     0.020925
CryoSleep      0.579016
Age            0.497336
dtype: float64

# correlation

In [315]:
corr1=df2.corr()

In [316]:
corr1

HomePlanet  CryoSleep       Age
HomePlanet    1.000000  -0.050933 -0.109894
CryoSleep    -0.050933   1.000000 -0.049338
Age          -0.109894  -0.049338  1.000000

# predicting the model

In [317]:
y_pred=model.predict(df2)

In [318]:
y_pred.shape

(4277,)

In [319]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [320]:
model.score(df2,y_pred)

1.0

In [321]:
a=df2["PassengerId"]

In [322]:
a.shape


(4277,)

In [323]:
x=pd.DataFrame(a)

In [324]:
x

PassengerId
0        0013_01
1        0018_01
2        0019_01
3        0021_01
4        0023_01
...          ...
4272     9266_02
4273     9269_01
4274     9271_01
4275     9273_01
4276     9277_01

[4277 rows x 1 columns]

In [325]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [326]:
b=y_pred

In [327]:
y=pd.DataFrame(b)

In [333]:
y.replace(0,False,inplace=True)
y.replace(1,True,inplace=True)

In [334]:
final=pd.concat([x,y],axis=1)

In [342]:
final.rename(columns = {0:'Transported'}, inplace = True)

In [343]:
final

PassengerId  Transported
0        0013_01        False
1        0018_01        False
2        0019_01        False
3        0021_01        False
4        0023_01        False
...          ...          ...
4272     9266_02        False
4273     9269_01        False
4274     9271_01        False
4275     9273_01        False
4276     9277_01        False

[4277 rows x 2 columns]

In [344]:
final.to_csv("spacetitanic",index=False)